### ISSUE TITLE
Core dump in Centos

### ISSUE THREAD

**Issue by eloycoto** [opentracing-contrib/nginx-opentracing#116]
Hello, 

I'm building ngx-opentracing for Openresty and each time that a request is in place I got the following core dump: 

```
Program terminated with signal 11, Segmentation fault.
#0  0x00007fc5343de0e3 in std::_Function_handler<opentracing::v2::expected<void, std::error_code> (opentracing::v2::string_view, opentracing::v2::string_view), jaegertracing::propagation::Propagator<opentracing::v2::HTTPHeadersReader const&, opentracing::v2::HTTPHeadersWriter const&>::extract(opentracing::v2::HTTPHeadersReader const&) const::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#1}>::_M_invoke(std::_Any_data const&, opentracing::v2::string_view&&, std::_Any_data const&) () from /usr/local/lib/libjaegertracing_plugin.so
Missing separate debuginfos, use: debuginfo-install openresty-1.15.8.2-6.el7.x86_64
(gdb) bt
#0  0x00007fc5343de0e3 in std::_Function_handler<opentracing::v2::expected<void, std::error_code> (opentracing::v2::string_view, opentracing::v2::string_view), jaegertracing::propagation::Propagator<opentracing::v2::HTTPHeadersReader const&, opentracing::v2::HTTPHeadersWriter const&>::extract(opentracing::v2::HTTPHeadersReader const&) const::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#1}>::_M_invoke(std::_Any_data const&, opentracing::v2::string_view&&, std::_Any_data const&) () from /usr/local/lib/libjaegertracing_plugin.so
#1  0x00007fc534d1ac36 in ?? () from /usr/local/openresty/nginx/modules/ngx_http_opentracing_module.so
#2  0x00007fc5343dbffe in jaegertracing::propagation::Propagator<opentracing::v2::HTTPHeadersReader const&, opentracing::v2::HTTPHeadersWriter const&>::extract(opentracing::v2::HTTPHeadersReader const&) const () from /usr/local/lib/libjaegertracing_plugin.so
#3  0x00007fc5343dc31a in jaegertracing::Tracer::Extract(opentracing::v2::HTTPHeadersReader const&) const ()
   from /usr/local/lib/libjaegertracing_plugin.so
#4  0x00007fc534d1ad2d in ngx_opentracing::extract_span_context(opentracing::v2::Tracer const&, ngx_http_request_s const*) ()
   from /usr/local/openresty/nginx/modules/ngx_http_opentracing_module.so
#5  0x00007fc534d208c4 in ngx_opentracing::RequestTracing::RequestTracing(ngx_http_request_s*, ngx_http_core_loc_conf_s*, ngx_opentracing::opentracing_loc_conf_t*, opentracing::v2::SpanContext const*) () from /usr/local/openresty/nginx/modules/ngx_http_opentracing_module.so
#6  0x00007fc534d1e961 in void std::vector<ngx_opentracing::RequestTracing, std::allocator<ngx_opentracing::RequestTracing> >::_M_emplace_back_aux<ngx_http_request_s*&, ngx_http_core_loc_conf_s*&, ngx_opentracing::opentracing_loc_conf_t*&>(ngx_http_request_s*&, ngx_http_core_loc_conf_s*&, ngx_opentracing::opentracing_loc_conf_t*&) () from /usr/local/openresty/nginx/modules/ngx_http_opentracing_module.so
#7  0x00007fc534d1e4e3 in ngx_opentracing::OpenTracingContext::OpenTracingContext(ngx_http_request_s*, ngx_http_core_loc_conf_s*, ngx_opentracing::opentracing_loc_conf_t*) () from /usr/local/openresty/nginx/modules/ngx_http_opentracing_module.so
#8  0x00007fc534d1d87e in ngx_opentracing::on_enter_block(ngx_http_request_s*) ()
   from /usr/local/openresty/nginx/modules/ngx_http_opentracing_module.so
#9  0x0000000000459bbc in ngx_http_core_rewrite_phase ()
#10 0x00000000004555f5 in ngx_http_core_run_phases ()
#11 0x00000000004605b1 in ?? ()
#12 0x0000000000460904 in ?? ()
#13 0x000000000044a027 in ?? ()
#14 0x0000000000440f9b in ngx_process_events_and_timers ()
#15 0x0000000000449780 in ngx_single_process_cycle ()
#16 0x000000000042181a in main ()
(gdb)
```

The way that I installed is the following spec + with the following change: 

Spec: 
https://github.com/openresty/openresty-packaging/blob/master/rpm/SPECS/openresty.spec

Config:
```
build
./configure \
    --prefix="%{orprefix}" \
    --with-cc-opt="-DNGX_LUA_ABORT_AT_PANIC -I%{zlib_prefix}/include -I%{pcre_prefix}/include -I%{openssl_prefix}/include" \
    --with-ld-opt="-L%{zlib_prefix}/lib -L%{pcre_prefix}/lib -L%{openssl_prefix}/lib -Wl,-rpath,%{zlib_prefix}/lib:%{pcre_prefix}/lib:%{openssl_prefix}/lib" \
    --with-pcre-jit \
    --without-http_rds_json_module \
    --without-http_rds_csv_module \
    --without-lua_rds_parser \
    --with-stream \
    --with-stream_ssl_module \
    --with-stream_ssl_preread_module \
    --with-http_v2_module \
    --without-mail_pop3_module \
    --without-mail_imap_module \
    --without-mail_smtp_module \
    --with-http_stub_status_module \
    --with-http_realip_module \
    --with-http_addition_module \
    --with-http_auth_request_module \
    --with-http_secure_link_module \
    --with-http_random_index_module \
    --with-http_gzip_static_module \
    --with-http_sub_module \
    --with-http_dav_module \
    --with-http_flv_module \
    --with-http_mp4_module \
    --with-http_gunzip_module \
    --with-threads \
    --with-luajit-xcflags='-DLUAJIT_NUMMODE=2 -DLUAJIT_ENABLE_LUA52COMPAT' \
    --with-dtrace-probes \
    --add-dynamic-module="/tmp/nginx-opentracing-0.9.0/opentracing" \
    %{?_smp_mflags}
```

It happens to me with 0.3.0 version, and I tried with the latest stable and always happens, any idea where this fails come from?

I tried the example in Openresty-dockerfile and worked perfectly. Any hint here?

Regards

**Comment by eloycoto** [comment]
@rnburn could you provide any help here?

This is the full backtrace is here: 
https://gist.github.com/eloycoto/e000b5fc278e718702ceac04e033894c

And here you have how to reproduce (Dockerfiles, config, etc..): 
https://gist.github.com/eloycoto/d1b4ada815ec7f3980069cdd0e66e194


Regards

**Comment by eloycoto** [comment]
Related to: https://github.com/jaegertracing/jaeger-client-cpp/issues/159
